# Generated by Django 3.1.5 on 2021-01-21 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210121_1605'),
        ('chat', '0002_auto_20210119_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='user.usercostumer'),
        ),
    ]
