# Generated by Django 3.1.5 on 2021-01-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210121_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat_log',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='chat_log',
            name='room_name',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
