# Generated by Django 3.1.5 on 2021-01-21 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usercostumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=30)),
                ('profil', models.ImageField(default='default.jpg', height_field='height_field', upload_to='media/image', width_field='width_field')),
                ('bio', models.CharField(default='Hey aku memakai apa ini', max_length=150)),
                ('status', models.CharField(choices=[('ada', 'ada'), ('busy', 'busy')], max_length=20)),
                ('width_field', models.PositiveIntegerField(default=0)),
                ('height_field', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
