# Generated by Django 3.1.5 on 2021-01-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercostumer',
            name='profil',
            field=models.ImageField(default='media/default.jpg', height_field='height_field', upload_to='image', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='usercostumer',
            name='status',
            field=models.CharField(choices=[('ada', 'ada'), ('busy', 'busy')], default='ada', max_length=20),
        ),
    ]
