# Generated by Django 3.1.5 on 2021-01-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210121_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercostumer',
            name='profil',
            field=models.ImageField(default='image/default.jpg', height_field='height_field', upload_to='image', width_field='width_field'),
        ),
    ]
